# Generated by Django 5.1.6 on 2025-03-01 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('password_confirmation', models.CharField(max_length=128, verbose_name='Confirm Password')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('industry', models.CharField(choices=[('retail', 'Retail'), ('ecommerce', 'E-Commerce'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50, verbose_name='Industry')),
                ('company_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50, verbose_name='Company Size')),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Revenue')),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('finance_manager', 'Finance Manager'), ('other', 'Other')], max_length=50, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
