# Generated by Django 5.1.6 on 2025-03-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
