# Generated by Django 5.1.6 on 2025-03-04 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units_sold', models.IntegerField()),
                ('manufacturing_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('gross_sales', models.FloatField()),
                ('discounts', models.FloatField()),
                ('sales', models.FloatField()),
                ('cogs', models.FloatField()),
                ('profit', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_forecast', models.FloatField(blank=True, null=True)),
                ('cogs_forecast', models.FloatField(blank=True, null=True)),
                ('profit_forecast', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
